[package]
name = "Lab3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ciphers = "0.1.0"
hex = "0.4.3"
hex-literal = "0.3.4"
rand = "0.8.5"
rsa = "0.7.2"
sha1 = "0.10.5"
